export class ResponseUpdateEmployProfile{
    appliedCount: number;
    companyDesc: string;
    companyLogo: string;
    companyName: string;
    companyUrl: string;
    createdAt: any;
    createdBy: string;
    deleted: boolean;
    eligibility: any;
    employerId: any;
    eventDate: any;
    eventLocation: string;
    fromSalary: number;
    id: string;
    jobDescription:string;
    jobLocation: string;
    jobType: string;
    lastDateToApply: number;
    passoutYearBatch: string;
    position: string;
    postedJobDate: any;
    postedJobNumber: number;
    requiredExperience: number;
    requiredSkillsMandatory: string;
    requiredSkillsPreferred:string;
    specialNoteTitle1: Array<string>;
    specialNoteTitle2: string;
    specialNoteTitle3: string;
    specialNotes1: string;
    specialNotes2: string;
    specialNotes3: string;
    toSalary: number;
    totalRequirement:number;
    updatedAt: any;
    updatedBy: string;
    verifiedByAdmin: boolean;
    verifierName: string;
}